spring.application.name=streaming

spring.servlet.multipart.max-file-size=1000MB
spring.servlet.multipart.max-request-size=1000MB
management.otlp.metrics.export.url=http://localhost:4318/v1/metrics
management.opentelemetry.logging.export.otlp.endpoint=http://localhost:4318/v1/logs
management.opentelemetry.tracing.export.otlp.endpoint=http://localhost:4318/v1/traces